const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const typeRouter = require('./typeRouter')
const taskRouter = require('./taskRouter')
const profileRouter = require('./profileRouter')
const responseRouter = require('./responseRouter')
const taskAcceptanceRouter = require('./taskAcceptanceRouter')
const reviewRouter = require('./reviewRouter')
const statisticRouter = require('./statisticRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/task', taskRouter)
router.use('/profile', profileRouter)
router.use('/response', responseRouter)
router.use('/acceptance', taskAcceptanceRouter)
router.use('/review', reviewRouter)
router.use('/statistics', statisticRouter)

module.exports = router
