export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const PROFILE_ROUTE = '/profile'
export const TASK_ROUTE = '/task'
export const MYTASKS_ROUTE = '/mytasks'
export const MYPROFILE_ROUTE = '/myprofile'
