const TASK_STATUS_PUBLISHED = 'PUBLISHED'
const TASK_STATUS_IN_PROGRESS = 'IN_PROGRESS'
const TASK_STATUS_READY = 'READY'
const PAGE_SIZE = 9;

module.exports = {
    TASK_STATUS_PUBLISHED,
    TASK_STATUS_IN_PROGRESS,
    TASK_STATUS_READY,
    PAGE_SIZE,
}